### ISSUE TITLE
Error: Plugin AclExtras could not be found

### ISSUE THREAD

**Issue by benny33** [markstory/acl_extras#21]
HI,

I read issue #18 and #19 and still can't fix my problem.

Running in Centos 6:

```
# Console/cake AclExtras.AclExtras aco_sync
# Console/cake AclExtras.AclExtras -h

#0 /var/www/cake/lib/Cake/Core/App.php(364): CakePlugin::path('AclExtras')
#1 /var/www/cake/lib/Cake/Core/App.php(225): App::pluginPath('AclExtras')
#2 /var/www/cake/lib/Cake/Core/App.php(542): App::path('Console/Command', 'AclExtras')
#3 [internal function]: App::load('AclExtrasShell')
#4 [internal function]: spl_autoload_call('AclExtrasShell')
#5 /var/www/cake/lib/Cake/Console/ShellDispatcher.php(240): class_exists('AclExtrasShell')
#6 /var/www/cake/lib/Cake/Console/ShellDispatcher.php(191): ShellDispatcher->_getShell('AclExtras.AclEx...')
#7 /var/www/cake/lib/Cake/Console/ShellDispatcher.php(69): ShellDispatcher->dispatch()
#8 /var/www/cake/app/Console/cake.php(33): ShellDispatcher::run(Array)
#9 {main}
```

I'm using CakePHP v2.2.0

My folder structure:
/app/Plugin/AclExtras/Console/Command/AclExtrasShell.php
/app/Plugin/AclExtras/Test/...

I have this on bootstrap.php:
CakePlugin::load('AclExtras');

Is there anything that im missing?

Thanks.

**Comment by AnthonyDionise** [comment]
@markstory Hey I have the same problem, but the pluginPath method returns the correct path that the plugin is in. What else do you think couid be the problem?

**Comment by markstory** [comment]
@AnthonyDionise Other than the CakePlugin::load() line missing, I don't.

**Comment by mtrifunjagic** [comment]
@Win php cake.php acl_extras.acl_extras aco_sync
