### ISSUE TITLE
Shell class AclExtrasShell could not be found

### ISSUE THREAD

**Issue by lightbyte** [markstory/acl_extras#33]
Hi,
This could be like the other issues, but i checked the _App::uses('Controller', 'Controller');_ and it's not working.
I guess it's something different because it was working till 2 days ago and now I can't find where is the problem.

This is the output when i run the command  Console/cake AclExtras aco_sync:

```
Error: Shell class AclExtrasShell could not be found.
#0 /opt/cakephp2.3.9/lib/Cake/Console/ShellDispatcher.php(192): ShellDispatcher->_getShell('AclExtras')
#1 /opt/cakephp2.3.9/lib/Cake/Console/ShellDispatcher.php(68): ShellDispatcher->dispatch()
#2 /home/user/proyect/myapp/Console/cake.php(38): ShellDispatcher::run(Array)
#3 {main}
```

Thank you in advance!

**Comment by AnthonyDionise** [comment]
Hey @lightbyte,

How did you clear your cache?

I have no idea how to do that / what that is.

**Comment by lightbyte** [comment]
Cache files are made to save execution time. CakePHP has some cache configuration in the Config/core.php, at the end of the file. You will see something like this:
```php
Cache::config('_cake_core_', array(
	'engine' => $engine,
	'prefix' => $prefix . 'cake_core_',
	'path' => CACHE . 'persistent' . DS,
	'serialize' => ($engine === 'File'),
	'duration' => $duration,
	'mask'=>0666
));
```
You can see the last line 'mask'=>0666 is the file permissions that I want this files to have so any user can rewrite them.
You can find more information here: http://book.cakephp.org/2.0/en/core-libraries/caching.html
