### ISSUE TITLE
Lib update to 2.9.0 breaks acl_extras

### ISSUE THREAD

**Issue by WrDX** [markstory/acl_extras#43]
Running cake AclExtras.AclExtras aco_sync results in an error:

```PHP Fatal error:  Class 'Object' not found in <path>Plugin/AclExtras/Lib/AclExtras.php on line 26```

Editing AclExtras.php line 26 from:

```class AclExtras extends Object {```

to:

```class AclExtras extends CakeObject {```

fixes the issue.

**Comment by markstory** [comment]
Sounds like I'm missing an `App::use()` call.

**Comment by WrDX** [comment]
Doesn't it have to do with this 2.9.0 release note?

> The Object class has been deprecated due to upcoming PHP7 collisions. It has been renamed to CakeObject to avoid collisions with new PHP reserved words.

**Comment by markstory** [comment]
There was a backwards compatible alias added as well.

**Comment by markstory** [comment]
I think this is fixed now. I'll tag a new release when the travis builds complete.

**Comment by markstory** [comment]
I've also added a fix to cakephp/cakephp to resolve this. That change will be in 2.9.1
