### ISSUE TITLE
Broken backwards compatibility

### ISSUE THREAD

**Issue by freefri** [markstory/acl_extras#48]
This commit https://github.com/markstory/acl_extras/commit/b5ebffc2e0decb76b7779aff91aae65ceb29dfc6 is breaking compatibility with every old version of cakephp which did not implement CakeObject (e.g. cake 2.4)

I think it will be a good practice to create tags (github releases) with versions so people can know when braking changes are introduced. 

For example if https://github.com/markstory/acl_extras/commit/4d904422459c0a1ea1d65c802f325e20c37bfac2 is 1.0.0 (https://github.com/markstory/acl_extras/releases/tag/1.0.0), https://github.com/markstory/acl_extras/commit/90bcfcf could be 1.1.0 and the last https://github.com/markstory/acl_extras/commit/8e4ad7654e883602941a77276b68ca9f07c60d1e could be 2.1.0. Doing it in this way, will allow us to have a better track of the different versions and set automatic updates using composer for example.

**Comment by markstory** [comment]
I'll add tags tonight.

**Comment by markstory** [comment]
Instead of adding a 2.0 tag, I've updated the composer requirements and tagged 1.1.0 and 1.2.0
