### ISSUE TITLE
CakeObject

### ISSUE THREAD

**Issue by gabrieldissotti** [markstory/acl_extras#49]
Fatal error: Class 'CakeObject' not found in C:\wamp64\www\fatec_sys\app\Plugin\AclExtras\Lib\AclExtras.php on line 27

It is solved removing extends CakeObject, is this right?

**Comment by markstory** [comment]
Have you tried upgrading AclExtras?

**Comment by gabrieldissotti** [comment]
Yes, was isn't solved, when i remove the "extends CakeObject" from my class it works normally.
