### ISSUE TITLE
CakeObject and Object

### ISSUE THREAD

**Issue by AimanMRT** [markstory/acl_extras#51]
Good day to all. and happy working. I want to ask a few question.

I just install acl extras plugin  to my folder project.

1st step i copy file from github and save to my project.
2nd step i put CakePlugin::load('AclExtras'); in my bootstrap.php.
3rd step i check cake AclExtras.AclExtras  -h i got problem which is CakeObject class not found in AclExtras.php line 27.

1st question how can i resolve this problem?? change 'CakeObject' to 'object' should be ok or not??

2nd question is where should i put the sentences like this
$this->Auth->authorize = 'actions';
$this->Auth->actionPath = 'controllers/';

im use CakePHP v2.6.4 (Welcome to CakePHP v2.6.4 Console)

**Comment by markstory** [comment]
> 1st question how can i resolve this problem?? change 'CakeObject' to 'object' should be ok or not??

Are you sure you're using the right version of AclExtras for the version of CakePHP you're using? `Object` was renamed to `CakeObject` during 2.x because PHP5 reserved `object` as a typehint. You can try editing the AclExtras files but there could be other problems.

> 2nd question is where should i put the sentences like this

In your controller. Generally that goes in `AppController` so that all your controller behave the same way.

**Comment by AimanMRT** [comment]
> > 1st question how can i resolve this problem?? change 'CakeObject' to 'object' should be ok or not??
> 
> Are you sure you're using the right version of AclExtras for the version of CakePHP you're using? `Object` was renamed to `CakeObject` during 2.x because PHP5 reserved `object` as a typehint. You can try editing the AclExtras files but there could be other problems.
> 
> > 2nd question is where should i put the sentences like this
> 
> In your controller. Generally that goes in `AppController` so that all your controller behave the same way.

1st..I just do change cakeobject to object..look everything been sync..but my new ctp file not sync in node..but i insert it manual use acl plugin..can be use for now..but i also need aclextras work normal to easy do work next time..

2nd..
I do create new funtion beforefilter and put the sentences inside..but my system was stop to run..😂😂..

**Comment by markstory** [comment]
>  I do create new funtion beforefilter and put the sentences inside..but my system was stop to run..😂😂..

I don't know what's going on there. You will have to figure that one out on your own.
